const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const path=require('path');
const app=express(); const server=http.createServer(app); const io=new Server(server);
app.use(express.static(path.join(__dirname,'public')));
const films=[
['The Dark Knight',2008,9.0,100,'جريمة • دراما','نادر','rare','https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'],
['Inception',2010,8.8,92,'خيال علمي • إثارة','مميز','special','https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg'],
['Interstellar',2014,8.7,88,'خيال علمي • دراما','مميز','special','https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'],
['The Godfather',1972,9.2,120,'جريمة • دراما','أسطوري','legendary','https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'],
['Fight Club',1999,8.8,84,'دراما • إثارة','مميز','special','https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg'],
['Forrest Gump',1994,8.8,90,'دراما • رومانسية','نادر','rare','https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg'],
['Gladiator',2000,8.5,78,'ملحمي • أكشن','عادي','common','https://image.tmdb.org/t/p/w500/ty8TnY2K0rQxazBM5J7x5Jw9b1L.jpg'],
['The Matrix',1999,8.7,86,'خيال علمي • أكشن','نادر','rare','https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg']
].map(x=>({name:x[0],year:x[1],rating:x[2],baseValue:x[3],genre:x[4],rarity:x[5],rarityClass:x[6],img:x[7]}));
const cinema={'The Dark Knight':{fame:99,awards:3,awardText:'فاز بأوسكار + 8 ترشيحات'},'Inception':{fame:97,awards:5,awardText:'4 أوسكارات + 8 ترشيحات'},'Interstellar':{fame:96,awards:1,awardText:'أوسكار + 5 ترشيحات'},'The Godfather':{fame:100,awards:6,awardText:'3 أوسكارات + 7 ترشيحات'},'Fight Club':{fame:94,awards:0,awardText:'ترشيحات وجوائز نقدية دون أوسكار'},'Forrest Gump':{fame:99,awards:8,awardText:'6 أوسكارات + 13 ترشيحًا'},'Gladiator':{fame:98,awards:6,awardText:'5 أوسكارات + 12 ترشيحًا'},'The Matrix':{fame:99,awards:5,awardText:'4 أوسكارات + جوائز تقنية متعددة'}};
const rooms=new Map(); function code(){let s;do{s='MZ'+Math.floor(1000+Math.random()*9000)}while(rooms.has(s));return s}
function pub(r){return {phase:r.phase,players:r.players.map(p=>({id:p.id,name:p.name,balance:p.balance,spent:p.spent,films:p.films,active:p.active,selectedFilmId:p.selectedFilmId})),round:r.round,rounds:r.rounds,film:r.film?{...r.film,value:undefined}:null,highest:r.highest,leader:r.leader,current:r.current,turnEndsAt:r.turnEndsAt,history:r.history,selectionTurnId:r.selectionTurnId,finalRanked:r.finalRanked}};
function broadcast(r){io.to(r.room).emit('state',pub(r));}
function getR(s){return rooms.get(s.room)}
function startAuction(r){if(r.round>=r.rounds){r.phase='selection';r.selectionTurnId=r.players.find(p=>p.films.length)?.id||null;r.players.forEach(p=>p.selectedFilmId=null);broadcast(r);return}const f={...r.pool[r.round++]};f.value=Math.max(30,Math.round(f.baseValue*(0.82+Math.random()*0.36)/10)*10);r.film=f;r.highest=0;r.leader=-1;r.players.forEach(p=>p.active=true);r.current=0;r.turnEndsAt=Date.now()+15000;broadcast(r);setTimeout(()=>turnTimeout(r.room),15050)}
function nextActive(r,from){for(let k=1;k<=r.players.length;k++){const i=(from+k)%r.players.length;if(r.players[i].active&&i!==r.leader)return i}return -1}
function turnTimeout(room){const r=rooms.get(room);if(!r||r.phase!=='auction'||Date.now()<r.turnEndsAt-100)return;if(r.leader===r.current||!r.players[r.current].active)return actionWithdraw(r,r.players[r.current].id);actionWithdraw(r,r.players[r.current].id)}
function restartTimer(r){r.turnEndsAt=Date.now()+15000;const room=r.room;setTimeout(()=>turnTimeout(room),15050);}
function actionWithdraw(r,id){const i=r.players.findIndex(p=>p.id===id);if(i<0||r.phase!=='auction'||i!==r.current||i===r.leader||!r.players[i].active)return;r.players[i].active=false;const others=r.players.filter((p,j)=>p.active&&j!==r.leader).length;if(others===0){if(r.leader>=0)sell(r);else noSale(r);return}r.current=nextActive(r,i);if(r.current<0){if(r.leader>=0)sell(r);else noSale(r);return}restartTimer(r);broadcast(r)}
function sell(r){const p=r.players[r.leader],paid=r.highest;const saving=r.film.value-paid;p.balance-=paid;p.spent+=paid;p.films.push({...r.film,price:paid,saving});r.history.push({film:r.film.name,player:p.name,price:paid});r.pendingDeal={sold:true,film:r.film.name,player:p.name,price:paid,value:r.film.value,diffText:`الفرق: ${saving>=0?'+':''}${saving} د.ك`,verdict:saving>=0?'🔥 صفقة ممتازة':'🟠 صفقة خاسرة',note:saving>=0?`وفّرت ${saving} د.ك عن القيمة.`:`دفعت ${-saving} د.ك فوق القيمة.`};r.phase='deal';broadcast(r);io.to(r.room).emit('deal',r.pendingDeal)}
function noSale(r){r.history.push({film:r.film.name,player:'لم يُبع',price:0});r.pendingDeal={sold:false,film:r.film.name,price:0,value:r.film.value,verdict:'لا صفقة',note:'لم يقدم أي لاعب مزايدة.'};r.phase='deal';broadcast(r);io.to(r.room).emit('deal',r.pendingDeal)}
function finalScore(f){const c=cinema[f.name]||{fame:50,awards:0};return c.fame*.45+(f.rating/10*100)*.35+Math.min(c.awards*5,25)*.2*4}
function makeFinal(r){const valid=r.players.filter(p=>p.films.some(f=>f.id===p.selectedFilmId));r.finalRanked=valid.map(p=>{const f=p.films.find(x=>x.id===p.selectedFilmId);const c=cinema[f.name]||{fame:50,awards:0,awardText:'بيانات محدودة'};return {player:p.name,film:f,fame:c.fame,awards:c.awards,awardText:c.awardText,total:finalScore(f)}}).sort((a,b)=>b.total-a.total);r.phase='final';broadcast(r)}
io.on('connection',socket=>{socket.on('createRoom',d=>{const r={room:code(),phase:'lobby',hostId:socket.id,budget:Math.max(20,+d.budget||500),playerCount:Math.min(6,Math.max(2,+d.playerCount||4)),rounds:Math.min(films.length,Math.max(1,+d.rounds||8)),players:[{id:socket.id,name:String(d.name||'لاعب').slice(0,20),balance:0,spent:0,films:[],active:true}],pool:[],round:0,history:[]};r.players[0].balance=r.budget;rooms.set(r.room,r);socket.join(r.room);socket.emit('roomCreated',{room:r.room,state:pub(r)})});
socket.on('joinRoom',d=>{const r=rooms.get(String(d.room||'').toUpperCase());if(!r)return socket.emit('errorMsg','الغرفة غير موجودة.');if(r.phase!=='lobby')return socket.emit('errorMsg','اللعبة بدأت بالفعل.');if(r.players.length>=r.playerCount)return socket.emit('errorMsg','الغرفة ممتلئة.');r.players.push({id:socket.id,name:String(d.name||'لاعب').slice(0,20),balance:r.budget,spent:0,films:[],active:true});socket.join(r.room);socket.emit('joined',{room:r.room,state:pub(r)});broadcast(r)});
socket.on('startGame',d=>{const r=getR(d);if(!r||socket.id!==r.hostId||r.phase!=='lobby')return;if(r.players.length<2)return socket.emit('errorMsg','يجب دخول لاعبين على الأقل.');r.pool=films.slice().sort(()=>Math.random()-.5).slice(0,r.rounds);r.phase='auction';r.round=0;startAuction(r)});
socket.on('bid',d=>{const r=getR(d);if(!r||r.phase!=='auction'||r.players[r.current]?.id!==socket.id||r.current===r.leader)return;const v=+d.value;if(!Number.isInteger(v)||v<10||v>500||v%10!==0)return socket.emit('errorMsg','المزايدة يجب أن تكون من 10 إلى 500 وبمضاعفات 10.');const p=r.players[r.current],np=r.highest+v;if(np>p.balance)return socket.emit('errorMsg','لا يمكنك تجاوز محفظتك.');r.leader=r.current;r.highest=np;r.current=nextActive(r,r.current);if(r.current<0)sell(r);else restartTimer(r),broadcast(r)});
socket.on('withdraw',d=>{const r=getR(d);if(r)actionWithdraw(r,socket.id)});
socket.on('nextAfterDeal',d=>{const r=getR(d);if(!r||r.phase!=='deal')return;r.phase='auction';startAuction(r)});
socket.on('selectFilm',d=>{const r=getR(d);if(!r||r.phase!=='selection'||r.selectionTurnId!==socket.id)return;const p=r.players.find(x=>x.id===socket.id);const f=p?.films?.[+d.index];if(!f)return;p.selectedFilmId=f.id||`${p.id}-${d.index}-${f.name}`;r.selectionTurnId=r.players.find(x=>x.films.length&&!x.selectedFilmId)?.id||null;if(!r.selectionTurnId)makeFinal(r);else broadcast(r)});
socket.on('disconnect',()=>{for(const r of rooms.values()){const i=r.players.findIndex(p=>p.id===socket.id);if(i>=0&&r.phase!=='final'){const name=r.players[i].name;r.players.splice(i,1);if(r.players.length<2){r.phase='lobby'}if(r.hostId===socket.id&&r.players[0])r.hostId=r.players[0].id;broadcast(r);io.to(r.room).emit('disconnectedPlayer',name);}}});});
const PORT=process.env.PORT||3000;server.listen(PORT,'0.0.0.0',()=>console.log(`Mazad Online running on http://localhost:${PORT}`));
